### ISSUE TITLE
Identify Courses

### ISSUE THREAD

**Issue by amazingrando** [fourkitchens/js-practice-group#10]
- [ ] Collect a master list of JS courses as fodder for training
- [ ] Compare the skills requirements from the other ticket #9 against the courses found to find the right ones for our training.

**Comment by flipactual** [comment]
https://github.com/kamranahmedse/developer-roadmap/blob/master/README.md#-front-end-roadmap

https://github.com/kamranahmedse/developer-roadmap/blob/master/README.md#-back-end-roadmap
